# Generated by Django 3.1.7 on 2021-06-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210625_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='yo', max_length=250),
            preserve_default=False,
        ),
    ]
